// <auto-generated />
using System;
using EmployeeSeriesManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeSeriesManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EmployeeSeriesDbContext))]
    partial class EmployeeSeriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Building")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Floor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MailboxNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("AddressType", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationalUnit")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ExternalId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.EmployeeAddress", b =>
                {
                    b.Property<int>("EmployeesExternalId")
                        .HasColumnType("int");

                    b.Property<int>("AddressesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesExternalId", "AddressesId");

                    b.HasIndex("AddressesId");

                    b.ToTable("EmployeesAddresses", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.EmployeeIdCard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("Validity")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesExternalId");

                    b.ToTable("EmployeesIdCards", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.EmployeeSeries", b =>
                {
                    b.Property<int>("EmployeesExternalId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeesExternalId", "SeriesCode", "StartDate");

                    b.HasIndex("SeriesCode");

                    b.ToTable("EmployeesSeries", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Series", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Code");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Address", b =>
                {
                    b.HasOne("EmployeeSeriesManagement.Domain.Entities.AddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressType");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.EmployeeAddress", b =>
                {
                    b.HasOne("EmployeeSeriesManagement.Domain.Entities.Address", "Address")
                        .WithMany("EmployeeAddresses")
                        .HasForeignKey("AddressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeSeriesManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeAddresses")
                        .HasForeignKey("EmployeesExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.EmployeeIdCard", b =>
                {
                    b.HasOne("EmployeeSeriesManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("IdCards")
                        .HasForeignKey("EmployeesExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.EmployeeSeries", b =>
                {
                    b.HasOne("EmployeeSeriesManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeSeries")
                        .HasForeignKey("EmployeesExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeSeriesManagement.Domain.Entities.Series", "Series")
                        .WithMany("EmployeeSeries")
                        .HasForeignKey("SeriesCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Address", b =>
                {
                    b.Navigation("EmployeeAddresses");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.AddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeAddresses");

                    b.Navigation("EmployeeSeries");

                    b.Navigation("IdCards");
                });

            modelBuilder.Entity("EmployeeSeriesManagement.Domain.Entities.Series", b =>
                {
                    b.Navigation("EmployeeSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
